{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rumil.fullname" . }}-api-secrets
  labels:
    {{- include "rumil.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.api }}
  {{- if and $value (kindIs "string" $value) }}
  {{ $key | upper }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
