// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CallOut
 */
export type CallOut = {
    /**
     * Id
     */
    id: string;
    call_type: CallType;
    workspace: Workspace;
    /**
     * Project Id
     */
    project_id: string;
    status: CallStatus;
    /**
     * Parent Call Id
     */
    parent_call_id: string | null;
    /**
     * Scope Page Id
     */
    scope_page_id: string | null;
    /**
     * Budget Allocated
     */
    budget_allocated: number | null;
    /**
     * Budget Used
     */
    budget_used: number;
    /**
     * Context Page Ids
     */
    context_page_ids: Array<string>;
    /**
     * Result Summary
     */
    result_summary: string;
    /**
     * Review Json
     */
    review_json: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
};

/**
 * CallStatus
 */
export type CallStatus = 'pending' | 'running' | 'complete' | 'failed';

/**
 * CallTraceOut
 */
export type CallTraceOut = {
    call: CallOut;
    /**
     * Events
     */
    events: Array<TraceEventOut>;
    /**
     * Children
     */
    children: Array<CallTraceOut>;
};

/**
 * CallType
 */
export type CallType = 'scout' | 'assess' | 'prioritization' | 'ingest' | 'reframe' | 'maintain';

/**
 * ConsiderationDirection
 */
export type ConsiderationDirection = 'supports' | 'opposes' | 'neutral';

/**
 * ConsiderationOut
 */
export type ConsiderationOut = {
    page: PageOut;
    link: PageLinkOut;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LLMExchangeOut
 */
export type LlmExchangeOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Phase
     */
    phase: string;
    /**
     * Round
     */
    round: number;
    /**
     * System Prompt
     */
    system_prompt: string | null;
    /**
     * User Message
     */
    user_message: string | null;
    /**
     * Response Text
     */
    response_text: string | null;
    /**
     * Tool Calls
     */
    tool_calls: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Input Tokens
     */
    input_tokens: number | null;
    /**
     * Output Tokens
     */
    output_tokens: number | null;
    /**
     * Error
     */
    error: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * LLMExchangeSummaryOut
 */
export type LlmExchangeSummaryOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Phase
     */
    phase: string;
    /**
     * Round
     */
    round: number;
    /**
     * Input Tokens
     */
    input_tokens: number | null;
    /**
     * Output Tokens
     */
    output_tokens: number | null;
    /**
     * Error
     */
    error: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * LinkType
 */
export type LinkType = 'consideration' | 'child_question' | 'supersedes' | 'related';

/**
 * PageCountsOut
 */
export type PageCountsOut = {
    /**
     * Considerations
     */
    considerations: number;
    /**
     * Judgements
     */
    judgements: number;
};

/**
 * PageLayer
 */
export type PageLayer = 'wiki' | 'squidgy';

/**
 * PageLinkOut
 */
export type PageLinkOut = {
    /**
     * Id
     */
    id: string;
    /**
     * From Page Id
     */
    from_page_id: string;
    /**
     * To Page Id
     */
    to_page_id: string;
    link_type: LinkType;
    direction: ConsiderationDirection | null;
    /**
     * Strength
     */
    strength: number;
    /**
     * Reasoning
     */
    reasoning: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PageOut
 */
export type PageOut = {
    /**
     * Id
     */
    id: string;
    page_type: PageType;
    layer: PageLayer;
    workspace: Workspace;
    /**
     * Content
     */
    content: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Epistemic Status
     */
    epistemic_status: number;
    /**
     * Epistemic Type
     */
    epistemic_type: string;
    /**
     * Provenance Model
     */
    provenance_model: string;
    /**
     * Provenance Call Type
     */
    provenance_call_type: string;
    /**
     * Provenance Call Id
     */
    provenance_call_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Superseded By
     */
    superseded_by: string | null;
    /**
     * Is Superseded
     */
    is_superseded: boolean;
    /**
     * Extra
     */
    extra: {
        [key: string]: unknown;
    };
};

/**
 * PageType
 */
export type PageType = 'source' | 'claim' | 'question' | 'judgement' | 'concept' | 'wiki';

/**
 * ProjectOut
 */
export type ProjectOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * QuestionTreeOut
 */
export type QuestionTreeOut = {
    question: PageOut;
    /**
     * Considerations
     */
    considerations: Array<ConsiderationOut>;
    /**
     * Judgements
     */
    judgements: Array<PageOut>;
    /**
     * Child Questions
     */
    child_questions: Array<QuestionTreeOut>;
};

/**
 * RealtimeConfigOut
 */
export type RealtimeConfigOut = {
    /**
     * Url
     */
    url: string;
    /**
     * Anon Key
     */
    anon_key: string;
};

/**
 * RunSummaryOut
 */
export type RunSummaryOut = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * RunTraceOut
 */
export type RunTraceOut = {
    /**
     * Run Id
     */
    run_id: string;
    question: PageOut | null;
    /**
     * Root Calls
     */
    root_calls: Array<CallTraceOut>;
};

/**
 * TraceEventOut
 */
export type TraceEventOut = {
    /**
     * Event
     */
    event: string;
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    };
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Workspace
 */
export type Workspace = 'research' | 'prioritization';

export type ListProjectsApiProjectsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type ListProjectsApiProjectsGetResponses = {
    /**
     * Response List Projects Api Projects Get
     *
     * Successful Response
     */
    200: Array<ProjectOut>;
};

export type ListProjectsApiProjectsGetResponse = ListProjectsApiProjectsGetResponses[keyof ListProjectsApiProjectsGetResponses];

export type ListPagesApiProjectsProjectIdPagesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Page Type
         */
        page_type?: PageType | null;
        /**
         * Workspace
         */
        workspace?: Workspace | null;
        /**
         * Active Only
         */
        active_only?: boolean;
    };
    url: '/api/projects/{project_id}/pages';
};

export type ListPagesApiProjectsProjectIdPagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPagesApiProjectsProjectIdPagesGetError = ListPagesApiProjectsProjectIdPagesGetErrors[keyof ListPagesApiProjectsProjectIdPagesGetErrors];

export type ListPagesApiProjectsProjectIdPagesGetResponses = {
    /**
     * Response List Pages Api Projects  Project Id  Pages Get
     *
     * Successful Response
     */
    200: Array<PageOut>;
};

export type ListPagesApiProjectsProjectIdPagesGetResponse = ListPagesApiProjectsProjectIdPagesGetResponses[keyof ListPagesApiProjectsProjectIdPagesGetResponses];

export type GetPageApiPagesPageIdGetData = {
    body?: never;
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: never;
    url: '/api/pages/{page_id}';
};

export type GetPageApiPagesPageIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPageApiPagesPageIdGetError = GetPageApiPagesPageIdGetErrors[keyof GetPageApiPagesPageIdGetErrors];

export type GetPageApiPagesPageIdGetResponses = {
    /**
     * Successful Response
     */
    200: PageOut;
};

export type GetPageApiPagesPageIdGetResponse = GetPageApiPagesPageIdGetResponses[keyof GetPageApiPagesPageIdGetResponses];

export type GetLinksFromApiPagesPageIdLinksFromGetData = {
    body?: never;
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: never;
    url: '/api/pages/{page_id}/links/from';
};

export type GetLinksFromApiPagesPageIdLinksFromGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLinksFromApiPagesPageIdLinksFromGetError = GetLinksFromApiPagesPageIdLinksFromGetErrors[keyof GetLinksFromApiPagesPageIdLinksFromGetErrors];

export type GetLinksFromApiPagesPageIdLinksFromGetResponses = {
    /**
     * Response Get Links From Api Pages  Page Id  Links From Get
     *
     * Successful Response
     */
    200: Array<PageLinkOut>;
};

export type GetLinksFromApiPagesPageIdLinksFromGetResponse = GetLinksFromApiPagesPageIdLinksFromGetResponses[keyof GetLinksFromApiPagesPageIdLinksFromGetResponses];

export type GetLinksToApiPagesPageIdLinksToGetData = {
    body?: never;
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: never;
    url: '/api/pages/{page_id}/links/to';
};

export type GetLinksToApiPagesPageIdLinksToGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLinksToApiPagesPageIdLinksToGetError = GetLinksToApiPagesPageIdLinksToGetErrors[keyof GetLinksToApiPagesPageIdLinksToGetErrors];

export type GetLinksToApiPagesPageIdLinksToGetResponses = {
    /**
     * Response Get Links To Api Pages  Page Id  Links To Get
     *
     * Successful Response
     */
    200: Array<PageLinkOut>;
};

export type GetLinksToApiPagesPageIdLinksToGetResponse = GetLinksToApiPagesPageIdLinksToGetResponses[keyof GetLinksToApiPagesPageIdLinksToGetResponses];

export type GetPageCountsApiPagesPageIdCountsGetData = {
    body?: never;
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: never;
    url: '/api/pages/{page_id}/counts';
};

export type GetPageCountsApiPagesPageIdCountsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPageCountsApiPagesPageIdCountsGetError = GetPageCountsApiPagesPageIdCountsGetErrors[keyof GetPageCountsApiPagesPageIdCountsGetErrors];

export type GetPageCountsApiPagesPageIdCountsGetResponses = {
    /**
     * Successful Response
     */
    200: PageCountsOut;
};

export type GetPageCountsApiPagesPageIdCountsGetResponse = GetPageCountsApiPagesPageIdCountsGetResponses[keyof GetPageCountsApiPagesPageIdCountsGetResponses];

export type ListRootQuestionsApiProjectsProjectIdQuestionsGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        workspace?: Workspace;
    };
    url: '/api/projects/{project_id}/questions';
};

export type ListRootQuestionsApiProjectsProjectIdQuestionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRootQuestionsApiProjectsProjectIdQuestionsGetError = ListRootQuestionsApiProjectsProjectIdQuestionsGetErrors[keyof ListRootQuestionsApiProjectsProjectIdQuestionsGetErrors];

export type ListRootQuestionsApiProjectsProjectIdQuestionsGetResponses = {
    /**
     * Response List Root Questions Api Projects  Project Id  Questions Get
     *
     * Successful Response
     */
    200: Array<PageOut>;
};

export type ListRootQuestionsApiProjectsProjectIdQuestionsGetResponse = ListRootQuestionsApiProjectsProjectIdQuestionsGetResponses[keyof ListRootQuestionsApiProjectsProjectIdQuestionsGetResponses];

export type GetQuestionTreeApiQuestionsQuestionIdTreeGetData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: {
        /**
         * Depth
         */
        depth?: number;
    };
    url: '/api/questions/{question_id}/tree';
};

export type GetQuestionTreeApiQuestionsQuestionIdTreeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionTreeApiQuestionsQuestionIdTreeGetError = GetQuestionTreeApiQuestionsQuestionIdTreeGetErrors[keyof GetQuestionTreeApiQuestionsQuestionIdTreeGetErrors];

export type GetQuestionTreeApiQuestionsQuestionIdTreeGetResponses = {
    /**
     * Successful Response
     */
    200: QuestionTreeOut;
};

export type GetQuestionTreeApiQuestionsQuestionIdTreeGetResponse = GetQuestionTreeApiQuestionsQuestionIdTreeGetResponses[keyof GetQuestionTreeApiQuestionsQuestionIdTreeGetResponses];

export type ListCallsApiProjectsProjectIdCallsGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Question Id
         */
        question_id?: string | null;
    };
    url: '/api/projects/{project_id}/calls';
};

export type ListCallsApiProjectsProjectIdCallsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCallsApiProjectsProjectIdCallsGetError = ListCallsApiProjectsProjectIdCallsGetErrors[keyof ListCallsApiProjectsProjectIdCallsGetErrors];

export type ListCallsApiProjectsProjectIdCallsGetResponses = {
    /**
     * Response List Calls Api Projects  Project Id  Calls Get
     *
     * Successful Response
     */
    200: Array<CallOut>;
};

export type ListCallsApiProjectsProjectIdCallsGetResponse = ListCallsApiProjectsProjectIdCallsGetResponses[keyof ListCallsApiProjectsProjectIdCallsGetResponses];

export type GetCallApiCallsCallIdGetData = {
    body?: never;
    path: {
        /**
         * Call Id
         */
        call_id: string;
    };
    query?: never;
    url: '/api/calls/{call_id}';
};

export type GetCallApiCallsCallIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCallApiCallsCallIdGetError = GetCallApiCallsCallIdGetErrors[keyof GetCallApiCallsCallIdGetErrors];

export type GetCallApiCallsCallIdGetResponses = {
    /**
     * Successful Response
     */
    200: CallOut;
};

export type GetCallApiCallsCallIdGetResponse = GetCallApiCallsCallIdGetResponses[keyof GetCallApiCallsCallIdGetResponses];

export type GetChildCallsApiCallsCallIdChildrenGetData = {
    body?: never;
    path: {
        /**
         * Call Id
         */
        call_id: string;
    };
    query?: never;
    url: '/api/calls/{call_id}/children';
};

export type GetChildCallsApiCallsCallIdChildrenGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChildCallsApiCallsCallIdChildrenGetError = GetChildCallsApiCallsCallIdChildrenGetErrors[keyof GetChildCallsApiCallsCallIdChildrenGetErrors];

export type GetChildCallsApiCallsCallIdChildrenGetResponses = {
    /**
     * Response Get Child Calls Api Calls  Call Id  Children Get
     *
     * Successful Response
     */
    200: Array<CallOut>;
};

export type GetChildCallsApiCallsCallIdChildrenGetResponse = GetChildCallsApiCallsCallIdChildrenGetResponses[keyof GetChildCallsApiCallsCallIdChildrenGetResponses];

export type GetRunTraceApiRunsRunIdTraceGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/runs/{run_id}/trace';
};

export type GetRunTraceApiRunsRunIdTraceGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunTraceApiRunsRunIdTraceGetError = GetRunTraceApiRunsRunIdTraceGetErrors[keyof GetRunTraceApiRunsRunIdTraceGetErrors];

export type GetRunTraceApiRunsRunIdTraceGetResponses = {
    /**
     * Successful Response
     */
    200: RunTraceOut;
};

export type GetRunTraceApiRunsRunIdTraceGetResponse = GetRunTraceApiRunsRunIdTraceGetResponses[keyof GetRunTraceApiRunsRunIdTraceGetResponses];

export type GetCallTraceApiCallsCallIdTraceGetData = {
    body?: never;
    path: {
        /**
         * Call Id
         */
        call_id: string;
    };
    query?: never;
    url: '/api/calls/{call_id}/trace';
};

export type GetCallTraceApiCallsCallIdTraceGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCallTraceApiCallsCallIdTraceGetError = GetCallTraceApiCallsCallIdTraceGetErrors[keyof GetCallTraceApiCallsCallIdTraceGetErrors];

export type GetCallTraceApiCallsCallIdTraceGetResponses = {
    /**
     * Successful Response
     */
    200: CallTraceOut;
};

export type GetCallTraceApiCallsCallIdTraceGetResponse = GetCallTraceApiCallsCallIdTraceGetResponses[keyof GetCallTraceApiCallsCallIdTraceGetResponses];

export type ListLlmExchangesApiCallsCallIdLlmExchangesGetData = {
    body?: never;
    path: {
        /**
         * Call Id
         */
        call_id: string;
    };
    query?: never;
    url: '/api/calls/{call_id}/llm-exchanges';
};

export type ListLlmExchangesApiCallsCallIdLlmExchangesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLlmExchangesApiCallsCallIdLlmExchangesGetError = ListLlmExchangesApiCallsCallIdLlmExchangesGetErrors[keyof ListLlmExchangesApiCallsCallIdLlmExchangesGetErrors];

export type ListLlmExchangesApiCallsCallIdLlmExchangesGetResponses = {
    /**
     * Response List Llm Exchanges Api Calls  Call Id  Llm Exchanges Get
     *
     * Successful Response
     */
    200: Array<LlmExchangeSummaryOut>;
};

export type ListLlmExchangesApiCallsCallIdLlmExchangesGetResponse = ListLlmExchangesApiCallsCallIdLlmExchangesGetResponses[keyof ListLlmExchangesApiCallsCallIdLlmExchangesGetResponses];

export type GetLlmExchangeApiLlmExchangesExchangeIdGetData = {
    body?: never;
    path: {
        /**
         * Exchange Id
         */
        exchange_id: string;
    };
    query?: never;
    url: '/api/llm-exchanges/{exchange_id}';
};

export type GetLlmExchangeApiLlmExchangesExchangeIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLlmExchangeApiLlmExchangesExchangeIdGetError = GetLlmExchangeApiLlmExchangesExchangeIdGetErrors[keyof GetLlmExchangeApiLlmExchangesExchangeIdGetErrors];

export type GetLlmExchangeApiLlmExchangesExchangeIdGetResponses = {
    /**
     * Successful Response
     */
    200: LlmExchangeOut;
};

export type GetLlmExchangeApiLlmExchangesExchangeIdGetResponse = GetLlmExchangeApiLlmExchangesExchangeIdGetResponses[keyof GetLlmExchangeApiLlmExchangesExchangeIdGetResponses];

export type GetRealtimeConfigApiRealtimeConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/realtime/config';
};

export type GetRealtimeConfigApiRealtimeConfigGetResponses = {
    /**
     * Successful Response
     */
    200: RealtimeConfigOut;
};

export type GetRealtimeConfigApiRealtimeConfigGetResponse = GetRealtimeConfigApiRealtimeConfigGetResponses[keyof GetRealtimeConfigApiRealtimeConfigGetResponses];

export type ListQuestionRunsApiQuestionsQuestionIdRunsGetData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/questions/{question_id}/runs';
};

export type ListQuestionRunsApiQuestionsQuestionIdRunsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListQuestionRunsApiQuestionsQuestionIdRunsGetError = ListQuestionRunsApiQuestionsQuestionIdRunsGetErrors[keyof ListQuestionRunsApiQuestionsQuestionIdRunsGetErrors];

export type ListQuestionRunsApiQuestionsQuestionIdRunsGetResponses = {
    /**
     * Response List Question Runs Api Questions  Question Id  Runs Get
     *
     * Successful Response
     */
    200: Array<RunSummaryOut>;
};

export type ListQuestionRunsApiQuestionsQuestionIdRunsGetResponse = ListQuestionRunsApiQuestionsQuestionIdRunsGetResponses[keyof ListQuestionRunsApiQuestionsQuestionIdRunsGetResponses];
