// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ABEvalDimensionOut
 */
export type AbEvalDimensionOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Preference
     */
    preference: string;
    /**
     * Report
     */
    report?: string;
    /**
     * Call Id
     */
    call_id?: string;
};

/**
 * ABEvalDimensionSummaryOut
 */
export type AbEvalDimensionSummaryOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Preference
     */
    preference: string;
};

/**
 * ABEvalReportListItemOut
 */
export type AbEvalReportListItemOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Run Id A
     */
    run_id_a: string;
    /**
     * Run Id B
     */
    run_id_b: string;
    /**
     * Question Id A
     */
    question_id_a?: string;
    /**
     * Question Id B
     */
    question_id_b?: string;
    /**
     * Question Headline
     */
    question_headline?: string;
    /**
     * Overall Assessment Preview
     */
    overall_assessment_preview?: string;
    /**
     * Preferences
     */
    preferences: Array<AbEvalDimensionSummaryOut>;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ABEvalReportOut
 */
export type AbEvalReportOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Run Id A
     */
    run_id_a: string;
    /**
     * Run Id B
     */
    run_id_b: string;
    /**
     * Question Id A
     */
    question_id_a?: string;
    /**
     * Question Id B
     */
    question_id_b?: string;
    /**
     * Question Headline
     */
    question_headline?: string;
    /**
     * Overall Assessment
     */
    overall_assessment: string;
    /**
     * Overall Assessment Call Id
     */
    overall_assessment_call_id?: string;
    /**
     * Eval Run Id
     */
    eval_run_id?: string;
    /**
     * Dimension Reports
     */
    dimension_reports: Array<AbEvalDimensionOut>;
    /**
     * Config A
     */
    config_a?: {
        [key: string]: unknown;
    };
    /**
     * Config B
     */
    config_b?: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AffectedPagesIdentifiedEventOut
 */
export type AffectedPagesIdentifiedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'affected_pages_identified';
    /**
     * Affected Pages
     */
    affected_pages: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * AgentStartedEventOut
 */
export type AgentStartedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'agent_started';
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * User Message
     */
    user_message: string;
};

/**
 * AuthUserOut
 */
export type AuthUserOut = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Admin
     */
    is_admin: boolean;
};

/**
 * AutocompactEventOut
 */
export type AutocompactEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'autocompact';
    /**
     * Agent Id
     */
    agent_id: string;
};

/**
 * Call
 */
export type Call = {
    call_type: CallType;
    workspace: Workspace;
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    status: CallStatus;
    /**
     * Parent Call Id
     */
    parent_call_id: string | null;
    /**
     * Scope Page Id
     */
    scope_page_id: string | null;
    /**
     * Budget Allocated
     */
    budget_allocated: number | null;
    /**
     * Budget Used
     */
    budget_used: number;
    /**
     * Context Page Ids
     */
    context_page_ids: Array<string>;
    /**
     * Result Summary
     */
    result_summary: string;
    /**
     * Review Json
     */
    review_json: {
        [key: string]: unknown;
    };
    /**
     * Call Params
     */
    call_params: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Sequence Id
     */
    sequence_id: string | null;
    /**
     * Sequence Position
     */
    sequence_position: number | null;
    /**
     * Cost Usd
     */
    cost_usd: number | null;
};

/**
 * CallNodeOut
 */
export type CallNodeOut = {
    call: CallSummary;
    /**
     * Scope Page Summary
     */
    scope_page_summary?: string | null;
    /**
     * Warning Count
     */
    warning_count?: number;
    /**
     * Error Count
     */
    error_count?: number;
};

/**
 * CallStatus
 */
export type CallStatus = 'pending' | 'running' | 'complete' | 'failed';

/**
 * CallSummary
 *
 * Lightweight Call representation for tree views — excludes bulky fields
 * like review_json, result_summary, and context_page_ids.
 */
export type CallSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Call Type
     */
    call_type: string;
    /**
     * Status
     */
    status: string;
    /**
     * Parent Call Id
     */
    parent_call_id: string | null;
    /**
     * Scope Page Id
     */
    scope_page_id: string | null;
    /**
     * Call Params
     */
    call_params: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Sequence Id
     */
    sequence_id: string | null;
    /**
     * Sequence Position
     */
    sequence_position: number | null;
    /**
     * Cost Usd
     */
    cost_usd: number | null;
};

/**
 * CallType
 */
export type CallType = 'find_considerations' | 'assess' | 'prioritization' | 'ingest' | 'reframe' | 'maintain' | 'summarize' | 'scout_subquestions' | 'scout_estimates' | 'scout_hypotheses' | 'scout_analogies' | 'scout_paradigm_cases' | 'scout_factchecks' | 'scout_web_questions' | 'scout_deep_questions' | 'scout_c_how_true' | 'scout_c_how_false' | 'scout_c_cruxes' | 'scout_c_relevant_evidence' | 'scout_c_stress_test_cases' | 'scout_c_robustify' | 'scout_c_strengthen' | 'web_research' | 'evaluate' | 'grounding_feedback' | 'feedback_update' | 'link_subquestions' | 'ab_eval' | 'ab_eval_comparison' | 'ab_eval_summary' | 'run_eval' | 'create_view' | 'global_prioritization' | 'update_view' | 'generate_spec' | 'generate_artefact' | 'critique_artefact' | 'critique_artefact_request_only' | 'refine_spec' | 'claude_code_direct' | 'versus_judge';

/**
 * CallTypeFruitScoreItem
 */
export type CallTypeFruitScoreItem = {
    /**
     * Call Type
     */
    call_type: string;
    /**
     * Fruit
     */
    fruit?: number;
    /**
     * Reasoning
     */
    reasoning?: string;
};

/**
 * CallsForQuestion
 */
export type CallsForQuestion = {
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Headline
     */
    headline: string | null;
    /**
     * By Type
     */
    by_type: {
        [key: string]: number;
    };
    /**
     * Total
     */
    total: number;
    /**
     * Child Questions
     */
    child_questions: number;
    /**
     * Considerations
     */
    considerations: number;
    /**
     * Judgements
     */
    judgements: number;
};

/**
 * Cell
 *
 * One aggregated (gen, judge, condition[, criterion]) cell.
 *
 * ``pct`` treats ties as 0.5. ``wins`` / ``ties`` / ``losses`` are the raw
 * counts that feed it (``n = wins + ties + losses``). ``tie_frac`` is the
 * share of judgments that were explicit ties — so a 50% cell from all-ties
 * visually contrasts with a 50/50 split. ``ci_lo`` / ``ci_hi`` is the
 * Wilson 95% interval on ``pct`` (None when ``n == 0``).
 */
export type Cell = {
    /**
     * Pct
     */
    pct: number | null;
    /**
     * N
     */
    n: number;
    /**
     * Wins
     */
    wins: number;
    /**
     * Ties
     */
    ties: number;
    /**
     * Losses
     */
    losses: number;
    /**
     * Tie Frac
     */
    tie_frac: number | null;
    /**
     * Ci Lo
     */
    ci_lo: number | null;
    /**
     * Ci Hi
     */
    ci_hi: number | null;
    /**
     * Bg
     */
    bg: string;
    /**
     * Fg
     */
    fg: string;
};

/**
 * ClaimReassessedEventOut
 */
export type ClaimReassessedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'claim_reassessed';
    /**
     * Old Page Id
     */
    old_page_id: string;
    /**
     * New Page Id
     */
    new_page_id: string;
    /**
     * Headline
     */
    headline: string;
};

/**
 * ClaimScoreItem
 */
export type ClaimScoreItem = {
    /**
     * Page Id
     */
    page_id: string;
    /**
     * Headline
     */
    headline?: string;
    /**
     * Impact
     */
    impact?: number | null;
    /**
     * Impact On Question
     */
    impact_on_question?: number;
    /**
     * Broader Impact
     */
    broader_impact?: number;
    /**
     * Fruit
     */
    fruit?: number;
    /**
     * Reasoning
     */
    reasoning?: string;
};

/**
 * ConditionMeta
 */
export type ConditionMeta = {
    /**
     * Title
     */
    title: string;
    /**
     * Pair
     */
    pair: string;
    /**
     * Cell Meaning
     */
    cell_meaning: string;
    /**
     * Value Picks
     */
    value_picks: string;
};

/**
 * ConsiderationDirection
 */
export type ConsiderationDirection = 'supports' | 'opposes' | 'neutral';

/**
 * ContextBuiltEventOut
 */
export type ContextBuiltEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'context_built';
    /**
     * Working Context Page Ids
     */
    working_context_page_ids: Array<PageRef>;
    /**
     * Preloaded Page Ids
     */
    preloaded_page_ids: Array<PageRef>;
    /**
     * Source Page Id
     */
    source_page_id: string | null;
    /**
     * Budget
     */
    budget: number | null;
    /**
     * Full Pages
     */
    full_pages: Array<PageRef>;
    /**
     * Abstract Pages
     */
    abstract_pages: Array<PageRef>;
    /**
     * Summary Pages
     */
    summary_pages: Array<PageRef>;
    /**
     * Distillation Pages
     */
    distillation_pages: Array<PageRef>;
    /**
     * Scope Linked Pages
     */
    scope_linked_pages: Array<PageRef>;
    /**
     * Budget Usage
     */
    budget_usage: {
        [key: string]: number;
    };
    /**
     * Context Text
     */
    context_text: string;
    /**
     * Context Text Chars
     */
    context_text_chars: number;
};

/**
 * CriterionMatrix
 */
export type CriterionMatrix = {
    /**
     * Criterion
     */
    criterion: string;
    /**
     * Cells
     */
    cells: Array<GenJudgeCell>;
};

/**
 * DedupeCandidateItem
 */
export type DedupeCandidateItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Headline
     */
    headline?: string;
    /**
     * Similarity
     */
    similarity: number;
    /**
     * Kept By Filter
     */
    kept_by_filter?: boolean;
};

/**
 * DegreeCell
 */
export type DegreeCell = {
    /**
     * Avg Out
     */
    avg_out: number;
    /**
     * Avg In
     */
    avg_in: number;
};

/**
 * DiagnosticsBundle
 *
 * Summary counts + three sections for the Diagnostics pane.
 *
 * `biased_judge_count` uses a |A%-50| > 5pp threshold so the banner
 * line matches the default color thresholds in the UI.
 */
export type DiagnosticsBundle = {
    /**
     * Judge Bias
     */
    judge_bias: Array<JudgeBiasRowOut>;
    /**
     * Biased Judge Count
     */
    biased_judge_count: number;
    /**
     * Small N Cells
     */
    small_n_cells: Array<SmallNCellOut>;
    /**
     * Essay Flags
     */
    essay_flags: Array<EssayFlagOut>;
};

/**
 * DispatchExecutedEventOut
 */
export type DispatchExecutedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'dispatch_executed';
    /**
     * Index
     */
    index: number;
    /**
     * Child Call Type
     */
    child_call_type: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Question Headline
     */
    question_headline: string;
    /**
     * Child Call Id
     */
    child_call_id: string | null;
};

/**
 * DispatchTraceItem
 */
export type DispatchTraceItem = {
    /**
     * Call Type
     */
    call_type: string;
    [key: string]: unknown;
};

/**
 * DispatchesPlannedEventOut
 */
export type DispatchesPlannedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'dispatches_planned';
    /**
     * Dispatches
     */
    dispatches: Array<DispatchTraceItem>;
};

/**
 * ErrorEventOut
 */
export type ErrorEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'error';
    /**
     * Message
     */
    message: string;
    /**
     * Phase
     */
    phase: string;
};

/**
 * EssayDetail
 *
 * Essay + the prompts shown to completion / judge / paraphrase models.
 */
export type EssayDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Author
     */
    author: string;
    /**
     * Pub Date
     */
    pub_date: string;
    /**
     * Url
     */
    url: string;
    /**
     * Markdown
     */
    markdown: string;
    /**
     * Schema Version
     */
    schema_version: number;
    /**
     * Prefix Config Hash
     */
    prefix_config_hash: string;
    /**
     * Target Words
     */
    target_words: number;
    /**
     * Completion Prompt
     */
    completion_prompt: string;
    /**
     * Judge System Prompt Template
     */
    judge_system_prompt_template: string;
    /**
     * Judge User Prompt Template
     */
    judge_user_prompt_template: string;
    /**
     * Judge Prompt Hash
     */
    judge_prompt_hash: string;
    /**
     * Paraphrase Prompt Template
     */
    paraphrase_prompt_template: string;
    /**
     * Criteria
     */
    criteria: Array<string>;
    /**
     * Prefix Variants
     */
    prefix_variants: Array<PrefixVariantInfo>;
    /**
     * Active Prefix Label
     */
    active_prefix_label: string;
};

/**
 * EssayFlagOut
 */
export type EssayFlagOut = {
    /**
     * Essay Id
     */
    essay_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * N Judgments
     */
    n_judgments: number;
    /**
     * Tie Rate Pct
     */
    tie_rate_pct: number;
    /**
     * Tie Flag
     */
    tie_flag: boolean;
    /**
     * Sweep Source
     */
    sweep_source: string | null;
    /**
     * Sweep N
     */
    sweep_n: number;
};

/**
 * EssayJudgmentsResponse
 *
 * Judgments for a single essay at one prefix variant.
 *
 * Rows whose ``prefix_config_hash`` doesn't match the selected variant
 * are filtered out of ``judgments``. They split into two buckets:
 *
 * - ``other_variant_hidden``: hash matches a *different* active prefix
 * variant for this essay (e.g. you're viewing ``no_headers`` and 227
 * rows belong to ``default``). Not stale — just a different cohort.
 * - ``stale_hidden``: hash matches no current variant. Genuinely stale
 * from essay re-import drift or a prefix-config bump.
 *
 * ``orphaned`` flags a judgment whose source_a / source_b is not
 * present in the current completions.jsonl at the same prefix_hash --
 * the judgment survived the variant check but its sources did not.
 */
export type EssayJudgmentsResponse = {
    /**
     * Judgments
     */
    judgments: Array<Judgment>;
    /**
     * Stale Hidden
     */
    stale_hidden: number;
    /**
     * Other Variant Hidden
     */
    other_variant_hidden: number;
};

/**
 * EssayMeta
 *
 * Headline metadata for one cached essay.
 */
export type EssayMeta = {
    /**
     * Id
     */
    id: string;
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Author
     */
    author: string;
    /**
     * Pub Date
     */
    pub_date: string;
    /**
     * Url
     */
    url: string;
    /**
     * Schema Version
     */
    schema_version: number;
};

/**
 * EssayStatus
 *
 * Per-essay state for the /results "essays" panel.
 *
 * Surfaces both validator output (clean? how many issues?) and the
 * current ``prefix_config_hash`` so a reader can spot when essay text
 * has drifted out from under cached judgments.
 */
export type EssayStatus = {
    /**
     * Essay Id
     */
    essay_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Schema Version
     */
    schema_version: number;
    /**
     * Current Prefix Hash
     */
    current_prefix_hash: string;
    /**
     * Validator Clean
     */
    validator_clean: boolean | null;
    /**
     * Validator Issues
     */
    validator_issues: number;
    /**
     * Validator Model
     */
    validator_model: string | null;
};

/**
 * EvaluationCompleteEventOut
 */
export type EvaluationCompleteEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'evaluation_complete';
    /**
     * Evaluation
     */
    evaluation: string;
};

/**
 * ExperimentalScoringCompletedEventOut
 */
export type ExperimentalScoringCompletedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'experimental_scoring_completed';
    /**
     * Subquestion Scores
     */
    subquestion_scores: Array<ExperimentalSubquestionScoreItem>;
    /**
     * Per Type Fruit
     */
    per_type_fruit: Array<CallTypeFruitScoreItem>;
};

/**
 * ExperimentalSubquestionScoreItem
 */
export type ExperimentalSubquestionScoreItem = {
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Headline
     */
    headline?: string;
    /**
     * Impact Curve
     */
    impact_curve?: string;
};

/**
 * ExplorePageEventOut
 */
export type ExplorePageEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'explore_page';
    /**
     * Page Id
     */
    page_id: string;
    /**
     * Page Headline
     */
    page_headline: string;
    /**
     * Response
     */
    response: string;
};

/**
 * GenJudgeCell
 *
 * One (gen_model, judge_model) cell with its rendered colors.
 */
export type GenJudgeCell = {
    /**
     * Gen Model
     */
    gen_model: string;
    /**
     * Judge Model
     */
    judge_model: string;
    cell: Cell;
};

/**
 * GlobalPhaseCompletedEventOut
 */
export type GlobalPhaseCompletedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'global_phase_completed';
    /**
     * Phase
     */
    phase: string;
    /**
     * Outcome
     */
    outcome: string;
};

/**
 * GroundingTasksGeneratedEventOut
 */
export type GroundingTasksGeneratedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'grounding_tasks_generated';
    /**
     * Task Count
     */
    task_count: number;
    /**
     * Tasks
     */
    tasks: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobListItem
 *
 * One row in GET /api/jobs. Built from a V1Job's metadata only.
 */
export type JobListItem = {
    /**
     * Job Name
     */
    job_name: string;
    /**
     * Namespace
     */
    namespace: string;
    /**
     * Status
     */
    status: 'pending' | 'running' | 'failed' | 'completed';
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Completed At
     */
    completed_at?: string | null;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Workspace
     */
    workspace: string;
    /**
     * Question
     */
    question: string;
    /**
     * Trace Url
     */
    trace_url: string;
    /**
     * Owner User Id
     */
    owner_user_id?: string;
    /**
     * Logs Url
     */
    logs_url?: string;
};

/**
 * JudgeBiasRowOut
 *
 * Per-judge A-preference breakdown.
 *
 * `all_*` covers every judged row; `cvc_*` covers only
 * completion-vs-completion pairs (neither side is human), which is the
 * pure-position-bias signal. `content_bias_pp` is the all - cvc gap in
 * percentage points; null when cvc n<20.
 */
export type JudgeBiasRowOut = {
    /**
     * Judge Base
     */
    judge_base: string;
    /**
     * N Total
     */
    n_total: number;
    /**
     * All A Pct
     */
    all_a_pct: number;
    /**
     * All Ci Lo Pct
     */
    all_ci_lo_pct: number;
    /**
     * All Ci Hi Pct
     */
    all_ci_hi_pct: number;
    /**
     * N Cvc
     */
    n_cvc: number;
    /**
     * Cvc A Pct
     */
    cvc_a_pct: number | null;
    /**
     * Cvc Ci Lo Pct
     */
    cvc_ci_lo_pct: number | null;
    /**
     * Cvc Ci Hi Pct
     */
    cvc_ci_hi_pct: number | null;
    /**
     * Content Bias Pp
     */
    content_bias_pp: number | null;
};

/**
 * JudgeLabel
 *
 * Stacked column-header parts for a judge model id.
 */
export type JudgeLabel = {
    /**
     * Variant
     */
    variant: string | null;
    /**
     * Model
     */
    model: string;
    /**
     * Task
     */
    task: string | null;
    /**
     * Phash
     */
    phash: string | null;
};

/**
 * Judgment
 *
 * One pairwise judgment row, shaped for the inspect view.
 *
 * Includes the full ``reasoning_text`` / ``prompt`` / ``system_prompt``
 * so the inspect UI can render them inline (matching the standalone
 * self-vs-human HTML viewer). Older rows may not have ``system_prompt``
 * or ``prompt`` populated; both are optional.
 */
export type Judgment = {
    /**
     * Judge Model
     */
    judge_model: string;
    /**
     * Judge Model Id
     */
    judge_model_id: string;
    /**
     * Config Hash
     */
    config_hash: string;
    /**
     * Prompt Hash
     */
    prompt_hash: string;
    /**
     * Sampling
     */
    sampling: {
        [key: string]: unknown;
    };
    /**
     * Criterion
     */
    criterion: string;
    /**
     * Source A
     */
    source_a: string;
    /**
     * Source B
     */
    source_b: string;
    /**
     * Display First
     */
    display_first: string;
    /**
     * Display Second
     */
    display_second: string;
    /**
     * Verdict
     */
    verdict: string | null;
    /**
     * Winner Source
     */
    winner_source: string | null;
    /**
     * Preference Label
     */
    preference_label: string | null;
    /**
     * Reasoning Preview
     */
    reasoning_preview: string;
    /**
     * Reasoning Text
     */
    reasoning_text: string | null;
    /**
     * Prompt
     */
    prompt: string | null;
    /**
     * System Prompt
     */
    system_prompt: string | null;
    /**
     * Is Rumil
     */
    is_rumil: boolean;
    /**
     * Rumil Trace Url
     */
    rumil_trace_url: string | null;
    /**
     * Rumil Question Id
     */
    rumil_question_id: string | null;
    /**
     * Rumil Call Id
     */
    rumil_call_id: string | null;
    /**
     * Rumil Run Id
     */
    rumil_run_id: string | null;
    /**
     * Rumil Cost Usd
     */
    rumil_cost_usd: number | null;
    /**
     * Contamination Note
     */
    contamination_note: string | null;
    /**
     * Orphaned
     */
    orphaned: boolean;
    /**
     * Prefix Config Hash
     */
    prefix_config_hash: string;
};

/**
 * JudgmentDetail
 *
 * Full judgment row for the side-panel inspector on /versus/results.
 *
 * Includes the verbatim prompt + reasoning text + raw provider response,
 * so a reader can audit what the judge actually saw and said. Most fields
 * are optional because the shape varies across judge variants (OpenRouter
 * vs anthropic vs rumil:text vs rumil:ws/orch).
 */
export type JudgmentDetail = {
    /**
     * Key
     */
    key: string;
    /**
     * Essay Id
     */
    essay_id: string;
    /**
     * Prefix Config Hash
     */
    prefix_config_hash: string;
    /**
     * Source A
     */
    source_a: string;
    /**
     * Source B
     */
    source_b: string;
    /**
     * Display First
     */
    display_first: string;
    /**
     * Display Second
     */
    display_second: string;
    /**
     * Criterion
     */
    criterion: string;
    /**
     * Judge Model
     */
    judge_model: string;
    /**
     * Judge Model Id
     */
    judge_model_id: string;
    /**
     * Config Hash
     */
    config_hash: string;
    /**
     * Prompt Hash
     */
    prompt_hash: string;
    /**
     * Sampling
     */
    sampling: {
        [key: string]: unknown;
    };
    /**
     * Verdict
     */
    verdict: string | null;
    /**
     * Winner Source
     */
    winner_source: string | null;
    /**
     * Preference Label
     */
    preference_label: string | null;
    /**
     * Is Rumil
     */
    is_rumil: boolean;
    /**
     * Contamination Note
     */
    contamination_note: string | null;
    /**
     * Prompt
     */
    prompt: string | null;
    /**
     * Reasoning Text
     */
    reasoning_text: string | null;
    /**
     * Raw Response
     */
    raw_response: {
        [key: string]: unknown;
    } | Array<unknown> | null;
    /**
     * Rumil Trace Url
     */
    rumil_trace_url: string | null;
    /**
     * Rumil Question Id
     */
    rumil_question_id: string | null;
    /**
     * Rumil Call Id
     */
    rumil_call_id: string | null;
    /**
     * Rumil Run Id
     */
    rumil_run_id: string | null;
    /**
     * Rumil Cost Usd
     */
    rumil_cost_usd: number | null;
    /**
     * Ts
     */
    ts: string | null;
    /**
     * Duration S
     */
    duration_s: number | null;
};

/**
 * JudgmentRow
 *
 * One row in the raw-judgments explorer at the bottom of /results.
 */
export type JudgmentRow = {
    /**
     * Key
     */
    key: string;
    /**
     * Essay Id
     */
    essay_id: string;
    /**
     * Prefix Config Hash
     */
    prefix_config_hash: string;
    /**
     * Source A
     */
    source_a: string;
    /**
     * Source B
     */
    source_b: string;
    /**
     * Criterion
     */
    criterion: string;
    /**
     * Judge Model
     */
    judge_model: string;
    /**
     * Judge Model Id
     */
    judge_model_id: string;
    /**
     * Config Hash
     */
    config_hash: string;
    /**
     * Verdict
     */
    verdict: string;
    /**
     * Winner
     */
    winner: string;
    /**
     * Preference Label
     */
    preference_label: string | null;
    /**
     * Ts
     */
    ts: string;
    /**
     * Is Rumil
     */
    is_rumil: boolean;
    /**
     * Contamination Note
     */
    contamination_note: string | null;
    /**
     * Stale
     */
    stale: boolean;
    /**
     * Orphaned
     */
    orphaned: boolean;
};

/**
 * LLMExchangeEventOut
 */
export type LlmExchangeEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'llm_exchange';
    /**
     * Exchange Id
     */
    exchange_id: string;
    /**
     * Phase
     */
    phase: string;
    /**
     * Round
     */
    round: number | null;
    /**
     * Input Tokens
     */
    input_tokens: number | null;
    /**
     * Output Tokens
     */
    output_tokens: number | null;
    /**
     * Cache Creation Input Tokens
     */
    cache_creation_input_tokens: number | null;
    /**
     * Cache Read Input Tokens
     */
    cache_read_input_tokens: number | null;
    /**
     * Duration Ms
     */
    duration_ms: number | null;
    /**
     * Cost Usd
     */
    cost_usd: number | null;
    /**
     * Has Thinking
     */
    has_thinking: boolean | null;
    /**
     * Tool Uses
     */
    tool_uses: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Langfuse Trace Url
     */
    langfuse_trace_url: string | null;
};

/**
 * LLMExchangeOut
 */
export type LlmExchangeOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Phase
     */
    phase: string;
    /**
     * Round
     */
    round: number | null;
    /**
     * System Prompt
     */
    system_prompt: string | null;
    /**
     * User Message
     */
    user_message: string | null;
    /**
     * User Messages
     */
    user_messages?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Response Text
     */
    response_text: string | null;
    /**
     * Tool Calls
     */
    tool_calls: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Input Tokens
     */
    input_tokens: number | null;
    /**
     * Output Tokens
     */
    output_tokens: number | null;
    /**
     * Duration Ms
     */
    duration_ms: number | null;
    /**
     * Error
     */
    error: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * LLMExchangeSummaryOut
 */
export type LlmExchangeSummaryOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Phase
     */
    phase: string;
    /**
     * Round
     */
    round: number | null;
    /**
     * Input Tokens
     */
    input_tokens: number | null;
    /**
     * Output Tokens
     */
    output_tokens: number | null;
    /**
     * Duration Ms
     */
    duration_ms: number | null;
    /**
     * Error
     */
    error: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * LinkRole
 */
export type LinkRole = 'direct' | 'structural';

/**
 * LinkSubquestionsCompleteEventOut
 */
export type LinkSubquestionsCompleteEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'link_subquestions_complete';
    /**
     * Proposed
     */
    proposed: Array<ProposedSubquestion>;
};

/**
 * LinkType
 */
export type LinkType = 'consideration' | 'child_question' | 'supersedes' | 'related' | 'answers' | 'variant' | 'summarizes' | 'cites' | 'depends_on' | 'view_item' | 'view_of' | 'meta_for' | 'spec_of' | 'artefact_of' | 'critique_of' | 'generated_from';

/**
 * LinkedPageOut
 */
export type LinkedPageOut = {
    page: Page;
    link: PageLink;
};

/**
 * LoadPageEventOut
 */
export type LoadPageEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'load_page';
    /**
     * Page Id
     */
    page_id: string;
    /**
     * Page Headline
     */
    page_headline: string;
    /**
     * Detail
     */
    detail: string;
    /**
     * Response
     */
    response: string;
};

/**
 * Matrix
 */
export type Matrix = {
    /**
     * Condition
     */
    condition: string;
    meta: ConditionMeta;
    /**
     * Cells
     */
    cells: Array<GenJudgeCell>;
};

/**
 * MoveTraceItem
 */
export type MoveTraceItem = {
    /**
     * Type
     */
    type: string;
    /**
     * Headline
     */
    headline?: string;
    /**
     * Page Refs
     */
    page_refs?: Array<PageRef>;
    [key: string]: unknown;
};

/**
 * MovesExecutedEventOut
 */
export type MovesExecutedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'moves_executed';
    /**
     * Moves
     */
    moves: Array<MoveTraceItem>;
};

/**
 * OrchestratorRunRequest
 *
 * Inputs for a remote orchestrator run.
 *
 * Mirrors the subset of `main.py` flags that are forwarded into the
 * in-pod CLI invocation. Flags that only make sense on the laptop
 * (--db, --executor, --staged, --env-file, --run-id-file, --cli-user-id)
 * are intentionally absent — the in-pod run is always `--db prod
 * --executor local`.
 *
 * Exactly one of `question` (start a new investigation) or
 * `continue_id` (resume an existing question by ID) must be set.
 */
export type OrchestratorRunRequest = {
    /**
     * Question
     */
    question?: string | null;
    /**
     * Continue Id
     */
    continue_id?: string | null;
    /**
     * Budget
     */
    budget: number;
    /**
     * Workspace
     */
    workspace: string;
    /**
     * Smoke Test
     */
    smoke_test?: boolean;
    /**
     * Quiet
     */
    quiet?: boolean;
    /**
     * Debug
     */
    debug?: boolean;
    /**
     * Force Twophase Recurse
     */
    force_twophase_recurse?: boolean;
    /**
     * No Trace
     */
    no_trace?: boolean;
    /**
     * Auto Summary
     */
    auto_summary?: boolean;
    /**
     * Auto Self Improve
     */
    auto_self_improve?: boolean;
    /**
     * Available Moves
     */
    available_moves?: string | null;
    /**
     * Available Calls
     */
    available_calls?: string | null;
    /**
     * View Variant
     */
    view_variant?: string | null;
    /**
     * Ingest Num Claims
     */
    ingest_num_claims?: number | null;
    /**
     * Run Name
     */
    run_name?: string | null;
    /**
     * Container Tag
     */
    container_tag?: string | null;
};

/**
 * OrchestratorRunResponse
 */
export type OrchestratorRunResponse = {
    /**
     * Job Name
     */
    job_name: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Logs Url
     */
    logs_url?: string;
    /**
     * Trace Url
     */
    trace_url?: string;
};

/**
 * Page
 */
export type Page = {
    page_type: PageType;
    layer: PageLayer;
    workspace: Workspace;
    /**
     * Content
     */
    content: string;
    /**
     * Headline
     */
    headline: string;
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Epistemic Status
     */
    epistemic_status: number;
    /**
     * Epistemic Type
     */
    epistemic_type: string;
    /**
     * Credence
     */
    credence: number | null;
    /**
     * Credence Reasoning
     */
    credence_reasoning: string | null;
    /**
     * Robustness
     */
    robustness: number | null;
    /**
     * Robustness Reasoning
     */
    robustness_reasoning: string | null;
    /**
     * Provenance Model
     */
    provenance_model: string;
    /**
     * Provenance Call Type
     */
    provenance_call_type: string;
    /**
     * Provenance Call Id
     */
    provenance_call_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Superseded By
     */
    superseded_by: string | null;
    /**
     * Is Superseded
     */
    is_superseded: boolean;
    /**
     * Extra
     */
    extra: {
        [key: string]: unknown;
    };
    /**
     * Abstract
     */
    abstract: string;
    /**
     * Fruit Remaining
     */
    fruit_remaining: number | null;
    /**
     * Sections
     */
    sections: Array<string> | null;
    /**
     * Meta Type
     */
    meta_type: string | null;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Hidden
     */
    hidden: boolean;
};

/**
 * PageCountsOut
 */
export type PageCountsOut = {
    /**
     * Considerations
     */
    considerations: number;
    /**
     * Judgements
     */
    judgements: number;
};

/**
 * PageDetailOut
 */
export type PageDetailOut = {
    page: Page;
    /**
     * Links From
     */
    links_from: Array<LinkedPageOut>;
    /**
     * Links To
     */
    links_to: Array<LinkedPageOut>;
};

/**
 * PageLayer
 */
export type PageLayer = 'wiki' | 'squidgy';

/**
 * PageLink
 */
export type PageLink = {
    /**
     * From Page Id
     */
    from_page_id: string;
    /**
     * To Page Id
     */
    to_page_id: string;
    link_type: LinkType;
    /**
     * Id
     */
    id: string;
    direction: ConsiderationDirection | null;
    /**
     * Strength
     */
    strength: number;
    /**
     * Reasoning
     */
    reasoning: string;
    role: LinkRole;
    /**
     * Importance
     */
    importance: number | null;
    /**
     * Section
     */
    section: string | null;
    /**
     * Position
     */
    position: number | null;
    /**
     * Impact On Parent Question
     */
    impact_on_parent_question: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Run Id
     */
    run_id: string;
};

/**
 * PageLoadEventOut
 */
export type PageLoadEventOut = {
    /**
     * Page Id
     */
    page_id: string;
    /**
     * Detail
     */
    detail: string;
    /**
     * Tags
     */
    tags: {
        [key: string]: string;
    };
};

/**
 * PageLoadStatsOut
 */
export type PageLoadStatsOut = {
    /**
     * Events
     */
    events: Array<PageLoadEventOut>;
    /**
     * Total
     */
    total: number;
    /**
     * Total Unique
     */
    total_unique: number;
    /**
     * Question Headlines
     */
    question_headlines: {
        [key: string]: string;
    };
};

/**
 * PageRef
 */
export type PageRef = {
    /**
     * Id
     */
    id: string;
    /**
     * Headline
     */
    headline?: string;
};

/**
 * PageType
 */
export type PageType = 'source' | 'claim' | 'question' | 'judgement' | 'wiki' | 'summary' | 'view' | 'view_item' | 'view_meta' | 'spec_item' | 'artefact';

/**
 * PaginatedPagesOut
 */
export type PaginatedPagesOut = {
    /**
     * Items
     */
    items: Array<Page>;
    /**
     * Total Count
     */
    total_count: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * PhaseSkippedEventOut
 */
export type PhaseSkippedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'phase_skipped';
    /**
     * Phase
     */
    phase: string;
    /**
     * Reason
     */
    reason: string;
};

/**
 * PrefixVariantInfo
 *
 * One prefix variant available in the active config.
 *
 * Surfaced on ResultsBundle so the /versus/results UI can render a
 * variant selector. ``id`` matches the yaml ``prefix.id`` /
 * ``prefix_variants[].id`` and is the value the UI passes back as
 * ``?prefix_label=<id>``.
 */
export type PrefixVariantInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * N Paragraphs
     */
    n_paragraphs: number;
    /**
     * Include Headers
     */
    include_headers: boolean;
};

/**
 * Project
 */
export type Project = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Hidden
     */
    hidden: boolean;
    /**
     * Owner User Id
     */
    owner_user_id: string | null;
};

/**
 * ProjectStatsOut
 */
export type ProjectStatsOut = {
    /**
     * Pages Total
     */
    pages_total: number;
    /**
     * Pages By Type
     */
    pages_by_type: {
        [key: string]: number;
    };
    /**
     * Links Total
     */
    links_total: number;
    /**
     * Links By Type
     */
    links_by_type: {
        [key: string]: number;
    };
    /**
     * Degree Matrix
     */
    degree_matrix: {
        [key: string]: {
            [key: string]: DegreeCell;
        };
    };
    /**
     * Robustness Histogram
     */
    robustness_histogram: {
        [key: string]: number;
    };
    /**
     * Credence Histogram
     */
    credence_histogram: {
        [key: string]: number;
    };
    /**
     * Calls Per Question
     */
    calls_per_question: Array<CallsForQuestion>;
    /**
     * Project Id
     */
    project_id: string;
};

/**
 * ProposedSubquestion
 */
export type ProposedSubquestion = {
    /**
     * Id
     */
    id: string;
    /**
     * Headline
     */
    headline?: string;
};

/**
 * ProvenanceAxis
 *
 * One axis of the provenance summary.
 *
 * ``description`` says what the value or hash is computed over, so
 * the operator knows what would change it. ``counts`` is value ->
 * row count over the surviving rows. ``current_values`` is the
 * mainline set (UI flags anything not in this list as non-current).
 * ``value_labels`` turns opaque hashes into readable strings where
 * derivable (e.g. a ``prefix_config_hash`` maps back to its
 * originating ``"essay_id / variant_id"``).
 */
export type ProvenanceAxis = {
    /**
     * Description
     */
    description: string;
    /**
     * Counts
     */
    counts: {
        [key: string]: number;
    };
    /**
     * Current Values
     */
    current_values: Array<string>;
    /**
     * Value Labels
     */
    value_labels: {
        [key: string]: string;
    };
};

/**
 * ProvenanceSummary
 *
 * Per-axis breakdown of what slice the aggregate sits on top of.
 *
 * ``axes`` is keyed by axis name; ``axis_order`` declares the panel
 * rendering order (set by the backend's ``versus.mainline.axis_order``)
 * so the FE doesn't maintain a parallel list. New axes appear
 * automatically in the right place.
 */
export type ProvenanceSummary = {
    /**
     * Axes
     */
    axes: {
        [key: string]: ProvenanceAxis;
    };
    /**
     * Axis Order
     */
    axis_order: Array<string>;
};

/**
 * QuestionDedupeEventOut
 */
export type QuestionDedupeEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'question_dedupe';
    /**
     * Proposed Headline
     */
    proposed_headline: string;
    /**
     * Parent Id
     */
    parent_id: string;
    /**
     * Parent Headline
     */
    parent_headline: string;
    /**
     * Candidates
     */
    candidates: Array<DedupeCandidateItem>;
    /**
     * Outcome
     */
    outcome: string;
    /**
     * Matched Page Id
     */
    matched_page_id: string | null;
    /**
     * Matched Headline
     */
    matched_headline: string;
    /**
     * Decision Reasoning
     */
    decision_reasoning: string;
};

/**
 * QuestionStatsOut
 */
export type QuestionStatsOut = {
    /**
     * Pages Total
     */
    pages_total: number;
    /**
     * Pages By Type
     */
    pages_by_type: {
        [key: string]: number;
    };
    /**
     * Links Total
     */
    links_total: number;
    /**
     * Links By Type
     */
    links_by_type: {
        [key: string]: number;
    };
    /**
     * Degree Matrix
     */
    degree_matrix: {
        [key: string]: {
            [key: string]: DegreeCell;
        };
    };
    /**
     * Robustness Histogram
     */
    robustness_histogram: {
        [key: string]: number;
    };
    /**
     * Credence Histogram
     */
    credence_histogram: {
        [key: string]: number;
    };
    /**
     * Calls Per Question
     */
    calls_per_question: Array<CallsForQuestion>;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Subgraph Page Count
     */
    subgraph_page_count: number;
    subgraph: Subgraph;
};

/**
 * RealtimeConfigOut
 */
export type RealtimeConfigOut = {
    /**
     * Url
     */
    url: string;
    /**
     * Anon Key
     */
    anon_key: string;
};

/**
 * ReassessTriggeredEventOut
 */
export type ReassessTriggeredEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'reassess_triggered';
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Question Headline
     */
    question_headline: string;
    /**
     * Child Call Id
     */
    child_call_id: string | null;
};

/**
 * RenderQuestionSubgraphEventOut
 */
export type RenderQuestionSubgraphEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'render_question_subgraph';
    /**
     * Page Id
     */
    page_id: string;
    /**
     * Page Headline
     */
    page_headline: string;
    /**
     * Response
     */
    response: string;
};

/**
 * ResultsBundle
 */
export type ResultsBundle = {
    /**
     * Conditions
     */
    conditions: Array<string>;
    /**
     * Criteria
     */
    criteria: Array<string>;
    /**
     * Active Criterion
     */
    active_criterion: string | null;
    /**
     * Gen Models
     */
    gen_models: Array<string>;
    /**
     * Judge Models
     */
    judge_models: Array<string>;
    /**
     * Judge Labels
     */
    judge_labels: {
        [key: string]: JudgeLabel;
    };
    /**
     * Main Matrices
     */
    main_matrices: Array<Matrix>;
    /**
     * Completion Per Source
     */
    completion_per_source: Array<SourceMatrix>;
    /**
     * Small Grid
     */
    small_grid: Array<SmallGridRow>;
    /**
     * Rows
     */
    rows: Array<JudgmentRow>;
    /**
     * Total Judgments
     */
    total_judgments: number;
    /**
     * Total Completions
     */
    total_completions: number;
    /**
     * Sources Summary
     */
    sources_summary: Array<SourceSummary>;
    /**
     * Essays Status
     */
    essays_status: Array<EssayStatus>;
    /**
     * Stale Count
     */
    stale_count: number;
    /**
     * Current Count
     */
    current_count: number;
    /**
     * Include Stale
     */
    include_stale: boolean;
    /**
     * Include Contaminated
     */
    include_contaminated: boolean;
    row_filter: RowFilter;
    /**
     * Rows Total Before Filter
     */
    rows_total_before_filter: number;
    /**
     * Prefix Variants
     */
    prefix_variants: Array<PrefixVariantInfo>;
    /**
     * Active Prefix Label
     */
    active_prefix_label: string;
    provenance: ProvenanceSummary;
};

/**
 * ReviewCompleteEventOut
 */
export type ReviewCompleteEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'review_complete';
    /**
     * Remaining Fruit
     */
    remaining_fruit: number | null;
    /**
     * Confidence
     */
    confidence: number | null;
};

/**
 * RowFilter
 *
 * Echoed back on ResultsBundle when the row list is filtered.
 *
 * Populated from ``?filter_gen=`` / ``?filter_judge=`` /
 * ``?filter_condition=`` / ``?filter_criterion=`` — the cell-drill-in
 * linkage from MatrixTable cells into the raw-judgments table below.
 */
export type RowFilter = {
    /**
     * Gen
     */
    gen: string | null;
    /**
     * Judge
     */
    judge: string | null;
    /**
     * Condition
     */
    condition: string | null;
    /**
     * Criterion
     */
    criterion: string | null;
};

/**
 * RunListItemOut
 */
export type RunListItemOut = {
    /**
     * Run Id
     */
    run_id?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Name
     */
    name?: string;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Question Summary
     */
    question_summary?: string | null;
    /**
     * Staged
     */
    staged?: boolean;
};

/**
 * RunSummaryOut
 */
export type RunSummaryOut = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Provenance Call Id
     */
    provenance_call_id?: string;
};

/**
 * RunTraceTreeOut
 */
export type RunTraceTreeOut = {
    /**
     * Run Id
     */
    run_id: string;
    question: Page | null;
    /**
     * Calls
     */
    calls: Array<CallNodeOut>;
    /**
     * Cost Usd
     */
    cost_usd?: number | null;
    /**
     * Staged
     */
    staged?: boolean;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
};

/**
 * ScoringCompletedEventOut
 */
export type ScoringCompletedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'scoring_completed';
    /**
     * Subquestion Scores
     */
    subquestion_scores: Array<SubquestionScoreItem>;
    /**
     * Claim Scores
     */
    claim_scores: Array<ClaimScoreItem>;
    /**
     * Parent Fruit
     */
    parent_fruit: number | null;
    /**
     * Parent Fruit Reasoning
     */
    parent_fruit_reasoning: string;
    /**
     * Per Type Fruit
     */
    per_type_fruit: Array<CallTypeFruitScoreItem>;
    /**
     * Dispatch Guidance
     */
    dispatch_guidance: string;
};

/**
 * SmallGridRow
 */
export type SmallGridRow = {
    /**
     * Condition
     */
    condition: string;
    /**
     * Per Crit
     */
    per_crit: Array<CriterionMatrix>;
};

/**
 * SmallNCellOut
 */
export type SmallNCellOut = {
    /**
     * Gen Model
     */
    gen_model: string;
    /**
     * Judge Base
     */
    judge_base: string;
    /**
     * Condition
     */
    condition: string;
    /**
     * Criterion
     */
    criterion: string;
    /**
     * N
     */
    n: number;
};

/**
 * Source
 *
 * One generated continuation (or the held-out human remainder).
 *
 * ``prompt`` is the verbatim completion prompt the model received,
 * stored on the row (legacy rows and the human baseline have no
 * prompt — the inspect UI falls back to the template in that case).
 */
export type Source = {
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Text
     */
    text: string;
    /**
     * Words
     */
    words: number;
    /**
     * Target
     */
    target: number;
    /**
     * Prompt
     */
    prompt: string | null;
    /**
     * Prefix Config Hash
     */
    prefix_config_hash: string;
    /**
     * Sampling Hash
     */
    sampling_hash: string | null;
    /**
     * Model Id
     */
    model_id: string | null;
};

/**
 * SourceMatrix
 *
 * A main matrix restricted to one essay source (e.g. forethought / redwood / carlsmith).
 *
 * Wraps a regular :class:`Matrix` so the gen/judge axes match the all-source
 * matrix above; ``source_id`` is the essay-source label rendered in the UI.
 */
export type SourceMatrix = {
    /**
     * Source Id
     */
    source_id: string;
    matrix: Matrix;
};

/**
 * SourceSummary
 */
export type SourceSummary = {
    /**
     * Source Id
     */
    source_id: string;
    /**
     * N
     */
    n: number;
    /**
     * Avg Words
     */
    avg_words: number;
    /**
     * Avg Delta Pct
     */
    avg_delta_pct: number;
};

/**
 * SubagentCompletedEventOut
 */
export type SubagentCompletedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'subagent_completed';
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Child Call Id
     */
    child_call_id: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Input Tokens
     */
    input_tokens: number | null;
    /**
     * Output Tokens
     */
    output_tokens: number | null;
    /**
     * Cache Creation Input Tokens
     */
    cache_creation_input_tokens: number | null;
    /**
     * Cache Read Input Tokens
     */
    cache_read_input_tokens: number | null;
    /**
     * Cost Usd
     */
    cost_usd: number | null;
};

/**
 * SubagentStartedEventOut
 */
export type SubagentStartedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'subagent_started';
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Agent Type
     */
    agent_type: string;
    /**
     * Child Call Id
     */
    child_call_id: string;
    /**
     * Prompt
     */
    prompt: string;
};

/**
 * Subgraph
 */
export type Subgraph = {
    /**
     * Nodes
     */
    nodes: Array<SubgraphNode>;
    /**
     * Edges
     */
    edges: Array<SubgraphEdge>;
};

/**
 * SubgraphEdge
 */
export type SubgraphEdge = {
    /**
     * From Page Id
     */
    from_page_id: string;
    /**
     * To Page Id
     */
    to_page_id: string;
    /**
     * Link Type
     */
    link_type: string;
};

/**
 * SubgraphNode
 */
export type SubgraphNode = {
    /**
     * Id
     */
    id: string;
    /**
     * Page Type
     */
    page_type: string;
    /**
     * Headline
     */
    headline: string | null;
    /**
     * Depth
     */
    depth: number;
};

/**
 * SubquestionScoreItem
 */
export type SubquestionScoreItem = {
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Headline
     */
    headline?: string;
    /**
     * Impact
     */
    impact?: number | null;
    /**
     * Impact On Question
     */
    impact_on_question?: number;
    /**
     * Broader Impact
     */
    broader_impact?: number;
    /**
     * Fruit
     */
    fruit?: number;
    /**
     * Reasoning
     */
    reasoning?: string;
};

/**
 * ToolCallEventOut
 */
export type ToolCallEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'tool_call';
    /**
     * Tool Name
     */
    tool_name: string;
    /**
     * Tool Input
     */
    tool_input: {
        [key: string]: unknown;
    };
    /**
     * Response
     */
    response: string;
};

/**
 * UpdatePlanCreatedEventOut
 */
export type UpdatePlanCreatedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'update_plan_created';
    /**
     * Wave Count
     */
    wave_count: number;
    /**
     * Operation Count
     */
    operation_count: number;
    /**
     * Waves
     */
    waves: Array<Array<{
        [key: string]: unknown;
    }>>;
};

/**
 * UpdateSubgraphComputedEventOut
 */
export type UpdateSubgraphComputedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'update_subgraph_computed';
    /**
     * Node Count
     */
    node_count: number;
    /**
     * Nodes
     */
    nodes: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * UpdateViewPhaseCompletedEventOut
 */
export type UpdateViewPhaseCompletedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'update_view_phase_completed';
    /**
     * Phase
     */
    phase: string;
    /**
     * Items Processed
     */
    items_processed: number;
    /**
     * Items Modified
     */
    items_modified: number;
    /**
     * Items Created
     */
    items_created: number;
    /**
     * Items Removed
     */
    items_removed: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ViewCreatedEventOut
 */
export type ViewCreatedEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'view_created';
    /**
     * View Id
     */
    view_id: string;
    /**
     * View Headline
     */
    view_headline: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Superseded View Id
     */
    superseded_view_id: string | null;
};

/**
 * WarningEventOut
 */
export type WarningEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'warning';
    /**
     * Message
     */
    message: string;
};

/**
 * WebResearchCompleteEventOut
 */
export type WebResearchCompleteEventOut = {
    /**
     * Ts
     */
    ts: string;
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Event
     */
    event: 'web_research_complete';
    /**
     * Task Count
     */
    task_count: number;
    /**
     * Findings
     */
    findings: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Workspace
 */
export type Workspace = 'research' | 'prioritization';

export type CreateOrchestratorRunApiJobsOrchestratorRunsPostData = {
    body: OrchestratorRunRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/jobs/orchestrator-runs';
};

export type CreateOrchestratorRunApiJobsOrchestratorRunsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOrchestratorRunApiJobsOrchestratorRunsPostError = CreateOrchestratorRunApiJobsOrchestratorRunsPostErrors[keyof CreateOrchestratorRunApiJobsOrchestratorRunsPostErrors];

export type CreateOrchestratorRunApiJobsOrchestratorRunsPostResponses = {
    /**
     * Successful Response
     */
    201: OrchestratorRunResponse;
};

export type CreateOrchestratorRunApiJobsOrchestratorRunsPostResponse = CreateOrchestratorRunApiJobsOrchestratorRunsPostResponses[keyof CreateOrchestratorRunApiJobsOrchestratorRunsPostResponses];

export type ListJobsApiJobsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/jobs';
};

export type ListJobsApiJobsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListJobsApiJobsGetError = ListJobsApiJobsGetErrors[keyof ListJobsApiJobsGetErrors];

export type ListJobsApiJobsGetResponses = {
    /**
     * Response List Jobs Api Jobs Get
     *
     * Successful Response
     */
    200: Array<JobListItem>;
};

export type ListJobsApiJobsGetResponse = ListJobsApiJobsGetResponses[keyof ListJobsApiJobsGetResponses];

export type ListEssaysApiVersusEssaysGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Include Legacy
         */
        include_legacy?: boolean;
    };
    url: '/api/versus/essays';
};

export type ListEssaysApiVersusEssaysGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEssaysApiVersusEssaysGetError = ListEssaysApiVersusEssaysGetErrors[keyof ListEssaysApiVersusEssaysGetErrors];

export type ListEssaysApiVersusEssaysGetResponses = {
    /**
     * Response List Essays Api Versus Essays Get
     *
     * Successful Response
     */
    200: Array<EssayMeta>;
};

export type ListEssaysApiVersusEssaysGetResponse = ListEssaysApiVersusEssaysGetResponses[keyof ListEssaysApiVersusEssaysGetResponses];

export type GetEssayApiVersusEssaysEssayIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Essay Id
         */
        essay_id: string;
    };
    query?: {
        /**
         * Prefix Label
         */
        prefix_label?: string | null;
    };
    url: '/api/versus/essays/{essay_id}';
};

export type GetEssayApiVersusEssaysEssayIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEssayApiVersusEssaysEssayIdGetError = GetEssayApiVersusEssaysEssayIdGetErrors[keyof GetEssayApiVersusEssaysEssayIdGetErrors];

export type GetEssayApiVersusEssaysEssayIdGetResponses = {
    /**
     * Successful Response
     */
    200: EssayDetail;
};

export type GetEssayApiVersusEssaysEssayIdGetResponse = GetEssayApiVersusEssaysEssayIdGetResponses[keyof GetEssayApiVersusEssaysEssayIdGetResponses];

export type GetEssaySourcesApiVersusEssaysEssayIdSourcesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Essay Id
         */
        essay_id: string;
    };
    query?: {
        /**
         * Prefix Label
         */
        prefix_label?: string | null;
    };
    url: '/api/versus/essays/{essay_id}/sources';
};

export type GetEssaySourcesApiVersusEssaysEssayIdSourcesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEssaySourcesApiVersusEssaysEssayIdSourcesGetError = GetEssaySourcesApiVersusEssaysEssayIdSourcesGetErrors[keyof GetEssaySourcesApiVersusEssaysEssayIdSourcesGetErrors];

export type GetEssaySourcesApiVersusEssaysEssayIdSourcesGetResponses = {
    /**
     * Response Get Essay Sources Api Versus Essays  Essay Id  Sources Get
     *
     * Successful Response
     */
    200: Array<Source>;
};

export type GetEssaySourcesApiVersusEssaysEssayIdSourcesGetResponse = GetEssaySourcesApiVersusEssaysEssayIdSourcesGetResponses[keyof GetEssaySourcesApiVersusEssaysEssayIdSourcesGetResponses];

export type GetEssayJudgmentsApiVersusEssaysEssayIdJudgmentsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Essay Id
         */
        essay_id: string;
    };
    query?: {
        /**
         * Prefix Label
         */
        prefix_label?: string | null;
    };
    url: '/api/versus/essays/{essay_id}/judgments';
};

export type GetEssayJudgmentsApiVersusEssaysEssayIdJudgmentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEssayJudgmentsApiVersusEssaysEssayIdJudgmentsGetError = GetEssayJudgmentsApiVersusEssaysEssayIdJudgmentsGetErrors[keyof GetEssayJudgmentsApiVersusEssaysEssayIdJudgmentsGetErrors];

export type GetEssayJudgmentsApiVersusEssaysEssayIdJudgmentsGetResponses = {
    /**
     * Successful Response
     */
    200: EssayJudgmentsResponse;
};

export type GetEssayJudgmentsApiVersusEssaysEssayIdJudgmentsGetResponse = GetEssayJudgmentsApiVersusEssaysEssayIdJudgmentsGetResponses[keyof GetEssayJudgmentsApiVersusEssaysEssayIdJudgmentsGetResponses];

export type GetResultsApiVersusResultsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Criterion
         */
        criterion?: string | null;
        /**
         * Include Contaminated
         */
        include_contaminated?: boolean;
        /**
         * Include Stale
         */
        include_stale?: boolean;
        /**
         * Filter Gen
         */
        filter_gen?: string | null;
        /**
         * Filter Judge
         */
        filter_judge?: string | null;
        /**
         * Filter Condition
         */
        filter_condition?: string | null;
        /**
         * Filter Criterion
         */
        filter_criterion?: string | null;
        /**
         * Prefix Label
         */
        prefix_label?: string | null;
    };
    url: '/api/versus/results';
};

export type GetResultsApiVersusResultsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetResultsApiVersusResultsGetError = GetResultsApiVersusResultsGetErrors[keyof GetResultsApiVersusResultsGetErrors];

export type GetResultsApiVersusResultsGetResponses = {
    /**
     * Successful Response
     */
    200: ResultsBundle;
};

export type GetResultsApiVersusResultsGetResponse = GetResultsApiVersusResultsGetResponses[keyof GetResultsApiVersusResultsGetResponses];

export type GetJudgmentByKeyApiVersusJudgmentsByKeyGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Key
         */
        key: string;
    };
    url: '/api/versus/judgments/by-key';
};

export type GetJudgmentByKeyApiVersusJudgmentsByKeyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJudgmentByKeyApiVersusJudgmentsByKeyGetError = GetJudgmentByKeyApiVersusJudgmentsByKeyGetErrors[keyof GetJudgmentByKeyApiVersusJudgmentsByKeyGetErrors];

export type GetJudgmentByKeyApiVersusJudgmentsByKeyGetResponses = {
    /**
     * Successful Response
     */
    200: JudgmentDetail;
};

export type GetJudgmentByKeyApiVersusJudgmentsByKeyGetResponse = GetJudgmentByKeyApiVersusJudgmentsByKeyGetResponses[keyof GetJudgmentByKeyApiVersusJudgmentsByKeyGetResponses];

export type GetDiagnosticsApiVersusDiagnosticsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Criterion
         */
        criterion?: string | null;
        /**
         * Include Contaminated
         */
        include_contaminated?: boolean;
        /**
         * Include Stale
         */
        include_stale?: boolean;
        /**
         * Prefix Label
         */
        prefix_label?: string | null;
    };
    url: '/api/versus/diagnostics';
};

export type GetDiagnosticsApiVersusDiagnosticsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDiagnosticsApiVersusDiagnosticsGetError = GetDiagnosticsApiVersusDiagnosticsGetErrors[keyof GetDiagnosticsApiVersusDiagnosticsGetErrors];

export type GetDiagnosticsApiVersusDiagnosticsGetResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticsBundle;
};

export type GetDiagnosticsApiVersusDiagnosticsGetResponse = GetDiagnosticsApiVersusDiagnosticsGetResponses[keyof GetDiagnosticsApiVersusDiagnosticsGetResponses];

export type HealthzHealthzGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzHealthzGetResponses = {
    /**
     * Response Healthz Healthz Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthzHealthzGetResponse = HealthzHealthzGetResponses[keyof HealthzHealthzGetResponses];

export type GetMeApiAuthMeGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetMeApiAuthMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMeApiAuthMeGetError = GetMeApiAuthMeGetErrors[keyof GetMeApiAuthMeGetErrors];

export type GetMeApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: AuthUserOut;
};

export type GetMeApiAuthMeGetResponse = GetMeApiAuthMeGetResponses[keyof GetMeApiAuthMeGetResponses];

export type ListProjectsApiProjectsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/projects';
};

export type ListProjectsApiProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectsApiProjectsGetError = ListProjectsApiProjectsGetErrors[keyof ListProjectsApiProjectsGetErrors];

export type ListProjectsApiProjectsGetResponses = {
    /**
     * Response List Projects Api Projects Get
     *
     * Successful Response
     */
    200: Array<Project>;
};

export type ListProjectsApiProjectsGetResponse = ListProjectsApiProjectsGetResponses[keyof ListProjectsApiProjectsGetResponses];

export type GetProjectApiProjectsProjectIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}';
};

export type GetProjectApiProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectApiProjectsProjectIdGetError = GetProjectApiProjectsProjectIdGetErrors[keyof GetProjectApiProjectsProjectIdGetErrors];

export type GetProjectApiProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: Project;
};

export type GetProjectApiProjectsProjectIdGetResponse = GetProjectApiProjectsProjectIdGetResponses[keyof GetProjectApiProjectsProjectIdGetResponses];

export type ListProjectRunsApiProjectsProjectIdRunsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/runs';
};

export type ListProjectRunsApiProjectsProjectIdRunsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectRunsApiProjectsProjectIdRunsGetError = ListProjectRunsApiProjectsProjectIdRunsGetErrors[keyof ListProjectRunsApiProjectsProjectIdRunsGetErrors];

export type ListProjectRunsApiProjectsProjectIdRunsGetResponses = {
    /**
     * Response List Project Runs Api Projects  Project Id  Runs Get
     *
     * Successful Response
     */
    200: Array<RunListItemOut>;
};

export type ListProjectRunsApiProjectsProjectIdRunsGetResponse = ListProjectRunsApiProjectsProjectIdRunsGetResponses[keyof ListProjectRunsApiProjectsProjectIdRunsGetResponses];

export type ListPagesApiProjectsProjectIdPagesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Page Type
         */
        page_type?: PageType | null;
        /**
         * Workspace
         */
        workspace?: Workspace | null;
        /**
         * Active Only
         */
        active_only?: boolean;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Include Hidden
         */
        include_hidden?: boolean;
        /**
         * Staged Run Id
         */
        staged_run_id?: string | null;
    };
    url: '/api/projects/{project_id}/pages';
};

export type ListPagesApiProjectsProjectIdPagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPagesApiProjectsProjectIdPagesGetError = ListPagesApiProjectsProjectIdPagesGetErrors[keyof ListPagesApiProjectsProjectIdPagesGetErrors];

export type ListPagesApiProjectsProjectIdPagesGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedPagesOut;
};

export type ListPagesApiProjectsProjectIdPagesGetResponse = ListPagesApiProjectsProjectIdPagesGetResponses[keyof ListPagesApiProjectsProjectIdPagesGetResponses];

export type GetPageByShortIdApiPagesShortShortIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Short Id
         */
        short_id: string;
    };
    query?: {
        /**
         * Staged Run Id
         */
        staged_run_id?: string | null;
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/pages/short/{short_id}';
};

export type GetPageByShortIdApiPagesShortShortIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPageByShortIdApiPagesShortShortIdGetError = GetPageByShortIdApiPagesShortShortIdGetErrors[keyof GetPageByShortIdApiPagesShortShortIdGetErrors];

export type GetPageByShortIdApiPagesShortShortIdGetResponses = {
    /**
     * Successful Response
     */
    200: Page;
};

export type GetPageByShortIdApiPagesShortShortIdGetResponse = GetPageByShortIdApiPagesShortShortIdGetResponses[keyof GetPageByShortIdApiPagesShortShortIdGetResponses];

export type GetPageApiPagesPageIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: {
        /**
         * Staged Run Id
         */
        staged_run_id?: string | null;
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/pages/{page_id}';
};

export type GetPageApiPagesPageIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPageApiPagesPageIdGetError = GetPageApiPagesPageIdGetErrors[keyof GetPageApiPagesPageIdGetErrors];

export type GetPageApiPagesPageIdGetResponses = {
    /**
     * Successful Response
     */
    200: Page;
};

export type GetPageApiPagesPageIdGetResponse = GetPageApiPagesPageIdGetResponses[keyof GetPageApiPagesPageIdGetResponses];

export type GetLinksFromApiPagesPageIdLinksFromGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/pages/{page_id}/links/from';
};

export type GetLinksFromApiPagesPageIdLinksFromGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLinksFromApiPagesPageIdLinksFromGetError = GetLinksFromApiPagesPageIdLinksFromGetErrors[keyof GetLinksFromApiPagesPageIdLinksFromGetErrors];

export type GetLinksFromApiPagesPageIdLinksFromGetResponses = {
    /**
     * Response Get Links From Api Pages  Page Id  Links From Get
     *
     * Successful Response
     */
    200: Array<PageLink>;
};

export type GetLinksFromApiPagesPageIdLinksFromGetResponse = GetLinksFromApiPagesPageIdLinksFromGetResponses[keyof GetLinksFromApiPagesPageIdLinksFromGetResponses];

export type GetLinksToApiPagesPageIdLinksToGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/pages/{page_id}/links/to';
};

export type GetLinksToApiPagesPageIdLinksToGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLinksToApiPagesPageIdLinksToGetError = GetLinksToApiPagesPageIdLinksToGetErrors[keyof GetLinksToApiPagesPageIdLinksToGetErrors];

export type GetLinksToApiPagesPageIdLinksToGetResponses = {
    /**
     * Response Get Links To Api Pages  Page Id  Links To Get
     *
     * Successful Response
     */
    200: Array<PageLink>;
};

export type GetLinksToApiPagesPageIdLinksToGetResponse = GetLinksToApiPagesPageIdLinksToGetResponses[keyof GetLinksToApiPagesPageIdLinksToGetResponses];

export type GetDependentsApiPagesPageIdDependentsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: {
        /**
         * Include Hidden
         */
        include_hidden?: boolean;
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/pages/{page_id}/dependents';
};

export type GetDependentsApiPagesPageIdDependentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDependentsApiPagesPageIdDependentsGetError = GetDependentsApiPagesPageIdDependentsGetErrors[keyof GetDependentsApiPagesPageIdDependentsGetErrors];

export type GetDependentsApiPagesPageIdDependentsGetResponses = {
    /**
     * Response Get Dependents Api Pages  Page Id  Dependents Get
     *
     * Successful Response
     */
    200: Array<LinkedPageOut>;
};

export type GetDependentsApiPagesPageIdDependentsGetResponse = GetDependentsApiPagesPageIdDependentsGetResponses[keyof GetDependentsApiPagesPageIdDependentsGetResponses];

export type GetDependenciesApiPagesPageIdDependenciesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: {
        /**
         * Include Hidden
         */
        include_hidden?: boolean;
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/pages/{page_id}/dependencies';
};

export type GetDependenciesApiPagesPageIdDependenciesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDependenciesApiPagesPageIdDependenciesGetError = GetDependenciesApiPagesPageIdDependenciesGetErrors[keyof GetDependenciesApiPagesPageIdDependenciesGetErrors];

export type GetDependenciesApiPagesPageIdDependenciesGetResponses = {
    /**
     * Response Get Dependencies Api Pages  Page Id  Dependencies Get
     *
     * Successful Response
     */
    200: Array<LinkedPageOut>;
};

export type GetDependenciesApiPagesPageIdDependenciesGetResponse = GetDependenciesApiPagesPageIdDependenciesGetResponses[keyof GetDependenciesApiPagesPageIdDependenciesGetResponses];

export type GetPageDetailApiPagesPageIdDetailGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: {
        /**
         * Staged Run Id
         */
        staged_run_id?: string | null;
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/pages/{page_id}/detail';
};

export type GetPageDetailApiPagesPageIdDetailGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPageDetailApiPagesPageIdDetailGetError = GetPageDetailApiPagesPageIdDetailGetErrors[keyof GetPageDetailApiPagesPageIdDetailGetErrors];

export type GetPageDetailApiPagesPageIdDetailGetResponses = {
    /**
     * Successful Response
     */
    200: PageDetailOut;
};

export type GetPageDetailApiPagesPageIdDetailGetResponse = GetPageDetailApiPagesPageIdDetailGetResponses[keyof GetPageDetailApiPagesPageIdDetailGetResponses];

export type GetPageCountsApiPagesPageIdCountsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/pages/{page_id}/counts';
};

export type GetPageCountsApiPagesPageIdCountsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPageCountsApiPagesPageIdCountsGetError = GetPageCountsApiPagesPageIdCountsGetErrors[keyof GetPageCountsApiPagesPageIdCountsGetErrors];

export type GetPageCountsApiPagesPageIdCountsGetResponses = {
    /**
     * Successful Response
     */
    200: PageCountsOut;
};

export type GetPageCountsApiPagesPageIdCountsGetResponse = GetPageCountsApiPagesPageIdCountsGetResponses[keyof GetPageCountsApiPagesPageIdCountsGetResponses];

export type GetProjectStatsApiProjectsProjectIdStatsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Staged Run Id
         */
        staged_run_id?: string | null;
    };
    url: '/api/projects/{project_id}/stats';
};

export type GetProjectStatsApiProjectsProjectIdStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectStatsApiProjectsProjectIdStatsGetError = GetProjectStatsApiProjectsProjectIdStatsGetErrors[keyof GetProjectStatsApiProjectsProjectIdStatsGetErrors];

export type GetProjectStatsApiProjectsProjectIdStatsGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectStatsOut;
};

export type GetProjectStatsApiProjectsProjectIdStatsGetResponse = GetProjectStatsApiProjectsProjectIdStatsGetResponses[keyof GetProjectStatsApiProjectsProjectIdStatsGetResponses];

export type GetQuestionStatsApiPagesPageIdStatsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: {
        /**
         * Staged Run Id
         */
        staged_run_id?: string | null;
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/pages/{page_id}/stats';
};

export type GetQuestionStatsApiPagesPageIdStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionStatsApiPagesPageIdStatsGetError = GetQuestionStatsApiPagesPageIdStatsGetErrors[keyof GetQuestionStatsApiPagesPageIdStatsGetErrors];

export type GetQuestionStatsApiPagesPageIdStatsGetResponses = {
    /**
     * Successful Response
     */
    200: QuestionStatsOut;
};

export type GetQuestionStatsApiPagesPageIdStatsGetResponse = GetQuestionStatsApiPagesPageIdStatsGetResponses[keyof GetQuestionStatsApiPagesPageIdStatsGetResponses];

export type ListRootQuestionsApiProjectsProjectIdQuestionsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        workspace?: Workspace;
        /**
         * Include Hidden
         */
        include_hidden?: boolean;
    };
    url: '/api/projects/{project_id}/questions';
};

export type ListRootQuestionsApiProjectsProjectIdQuestionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRootQuestionsApiProjectsProjectIdQuestionsGetError = ListRootQuestionsApiProjectsProjectIdQuestionsGetErrors[keyof ListRootQuestionsApiProjectsProjectIdQuestionsGetErrors];

export type ListRootQuestionsApiProjectsProjectIdQuestionsGetResponses = {
    /**
     * Response List Root Questions Api Projects  Project Id  Questions Get
     *
     * Successful Response
     */
    200: Array<Page>;
};

export type ListRootQuestionsApiProjectsProjectIdQuestionsGetResponse = ListRootQuestionsApiProjectsProjectIdQuestionsGetResponses[keyof ListRootQuestionsApiProjectsProjectIdQuestionsGetResponses];

export type ListCallsApiProjectsProjectIdCallsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Question Id
         */
        question_id?: string | null;
    };
    url: '/api/projects/{project_id}/calls';
};

export type ListCallsApiProjectsProjectIdCallsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCallsApiProjectsProjectIdCallsGetError = ListCallsApiProjectsProjectIdCallsGetErrors[keyof ListCallsApiProjectsProjectIdCallsGetErrors];

export type ListCallsApiProjectsProjectIdCallsGetResponses = {
    /**
     * Response List Calls Api Projects  Project Id  Calls Get
     *
     * Successful Response
     */
    200: Array<Call>;
};

export type ListCallsApiProjectsProjectIdCallsGetResponse = ListCallsApiProjectsProjectIdCallsGetResponses[keyof ListCallsApiProjectsProjectIdCallsGetResponses];

export type GetCallApiCallsCallIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Call Id
         */
        call_id: string;
    };
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/calls/{call_id}';
};

export type GetCallApiCallsCallIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCallApiCallsCallIdGetError = GetCallApiCallsCallIdGetErrors[keyof GetCallApiCallsCallIdGetErrors];

export type GetCallApiCallsCallIdGetResponses = {
    /**
     * Successful Response
     */
    200: Call;
};

export type GetCallApiCallsCallIdGetResponse = GetCallApiCallsCallIdGetResponses[keyof GetCallApiCallsCallIdGetResponses];

export type GetChildCallsApiCallsCallIdChildrenGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Call Id
         */
        call_id: string;
    };
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/calls/{call_id}/children';
};

export type GetChildCallsApiCallsCallIdChildrenGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChildCallsApiCallsCallIdChildrenGetError = GetChildCallsApiCallsCallIdChildrenGetErrors[keyof GetChildCallsApiCallsCallIdChildrenGetErrors];

export type GetChildCallsApiCallsCallIdChildrenGetResponses = {
    /**
     * Response Get Child Calls Api Calls  Call Id  Children Get
     *
     * Successful Response
     */
    200: Array<Call>;
};

export type GetChildCallsApiCallsCallIdChildrenGetResponse = GetChildCallsApiCallsCallIdChildrenGetResponses[keyof GetChildCallsApiCallsCallIdChildrenGetResponses];

export type GetRunTraceTreeApiRunsRunIdTraceTreeGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/runs/{run_id}/trace-tree';
};

export type GetRunTraceTreeApiRunsRunIdTraceTreeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunTraceTreeApiRunsRunIdTraceTreeGetError = GetRunTraceTreeApiRunsRunIdTraceTreeGetErrors[keyof GetRunTraceTreeApiRunsRunIdTraceTreeGetErrors];

export type GetRunTraceTreeApiRunsRunIdTraceTreeGetResponses = {
    /**
     * Successful Response
     */
    200: RunTraceTreeOut;
};

export type GetRunTraceTreeApiRunsRunIdTraceTreeGetResponse = GetRunTraceTreeApiRunsRunIdTraceTreeGetResponses[keyof GetRunTraceTreeApiRunsRunIdTraceTreeGetResponses];

export type GetCallEventsApiCallsCallIdEventsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Call Id
         */
        call_id: string;
    };
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/calls/{call_id}/events';
};

export type GetCallEventsApiCallsCallIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCallEventsApiCallsCallIdEventsGetError = GetCallEventsApiCallsCallIdEventsGetErrors[keyof GetCallEventsApiCallsCallIdEventsGetErrors];

export type GetCallEventsApiCallsCallIdEventsGetResponses = {
    /**
     * Response Get Call Events Api Calls  Call Id  Events Get
     *
     * Successful Response
     */
    200: Array<({
        event: 'context_built';
    } & ContextBuiltEventOut) | ({
        event: 'moves_executed';
    } & MovesExecutedEventOut) | ({
        event: 'review_complete';
    } & ReviewCompleteEventOut) | ({
        event: 'llm_exchange';
    } & LlmExchangeEventOut) | ({
        event: 'warning';
    } & WarningEventOut) | ({
        event: 'error';
    } & ErrorEventOut) | ({
        event: 'scoring_completed';
    } & ScoringCompletedEventOut) | ({
        event: 'experimental_scoring_completed';
    } & ExperimentalScoringCompletedEventOut) | ({
        event: 'dispatches_planned';
    } & DispatchesPlannedEventOut) | ({
        event: 'dispatch_executed';
    } & DispatchExecutedEventOut) | ({
        event: 'explore_page';
    } & ExplorePageEventOut) | ({
        event: 'subagent_started';
    } & SubagentStartedEventOut) | ({
        event: 'subagent_completed';
    } & SubagentCompletedEventOut) | ({
        event: 'agent_started';
    } & AgentStartedEventOut) | ({
        event: 'evaluation_complete';
    } & EvaluationCompleteEventOut) | ({
        event: 'tool_call';
    } & ToolCallEventOut) | ({
        event: 'reassess_triggered';
    } & ReassessTriggeredEventOut) | ({
        event: 'affected_pages_identified';
    } & AffectedPagesIdentifiedEventOut) | ({
        event: 'update_subgraph_computed';
    } & UpdateSubgraphComputedEventOut) | ({
        event: 'update_plan_created';
    } & UpdatePlanCreatedEventOut) | ({
        event: 'claim_reassessed';
    } & ClaimReassessedEventOut) | ({
        event: 'grounding_tasks_generated';
    } & GroundingTasksGeneratedEventOut) | ({
        event: 'web_research_complete';
    } & WebResearchCompleteEventOut) | ({
        event: 'render_question_subgraph';
    } & RenderQuestionSubgraphEventOut) | ({
        event: 'load_page';
    } & LoadPageEventOut) | ({
        event: 'link_subquestions_complete';
    } & LinkSubquestionsCompleteEventOut) | ({
        event: 'view_created';
    } & ViewCreatedEventOut) | ({
        event: 'autocompact';
    } & AutocompactEventOut) | ({
        event: 'phase_skipped';
    } & PhaseSkippedEventOut) | ({
        event: 'global_phase_completed';
    } & GlobalPhaseCompletedEventOut) | ({
        event: 'update_view_phase_completed';
    } & UpdateViewPhaseCompletedEventOut) | ({
        event: 'question_dedupe';
    } & QuestionDedupeEventOut)>;
};

export type GetCallEventsApiCallsCallIdEventsGetResponse = GetCallEventsApiCallsCallIdEventsGetResponses[keyof GetCallEventsApiCallsCallIdEventsGetResponses];

export type ListAbEvalsApiAbEvalsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/ab-evals';
};

export type ListAbEvalsApiAbEvalsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAbEvalsApiAbEvalsGetError = ListAbEvalsApiAbEvalsGetErrors[keyof ListAbEvalsApiAbEvalsGetErrors];

export type ListAbEvalsApiAbEvalsGetResponses = {
    /**
     * Response List Ab Evals Api Ab Evals Get
     *
     * Successful Response
     */
    200: Array<AbEvalReportListItemOut>;
};

export type ListAbEvalsApiAbEvalsGetResponse = ListAbEvalsApiAbEvalsGetResponses[keyof ListAbEvalsApiAbEvalsGetResponses];

export type GetAbEvalApiAbEvalsEvalIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Eval Id
         */
        eval_id: string;
    };
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/ab-evals/{eval_id}';
};

export type GetAbEvalApiAbEvalsEvalIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAbEvalApiAbEvalsEvalIdGetError = GetAbEvalApiAbEvalsEvalIdGetErrors[keyof GetAbEvalApiAbEvalsEvalIdGetErrors];

export type GetAbEvalApiAbEvalsEvalIdGetResponses = {
    /**
     * Successful Response
     */
    200: AbEvalReportOut;
};

export type GetAbEvalApiAbEvalsEvalIdGetResponse = GetAbEvalApiAbEvalsEvalIdGetResponses[keyof GetAbEvalApiAbEvalsEvalIdGetResponses];

export type ListLlmExchangesApiCallsCallIdLlmExchangesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Call Id
         */
        call_id: string;
    };
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/calls/{call_id}/llm-exchanges';
};

export type ListLlmExchangesApiCallsCallIdLlmExchangesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLlmExchangesApiCallsCallIdLlmExchangesGetError = ListLlmExchangesApiCallsCallIdLlmExchangesGetErrors[keyof ListLlmExchangesApiCallsCallIdLlmExchangesGetErrors];

export type ListLlmExchangesApiCallsCallIdLlmExchangesGetResponses = {
    /**
     * Response List Llm Exchanges Api Calls  Call Id  Llm Exchanges Get
     *
     * Successful Response
     */
    200: Array<LlmExchangeSummaryOut>;
};

export type ListLlmExchangesApiCallsCallIdLlmExchangesGetResponse = ListLlmExchangesApiCallsCallIdLlmExchangesGetResponses[keyof ListLlmExchangesApiCallsCallIdLlmExchangesGetResponses];

export type GetLlmExchangeApiLlmExchangesExchangeIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Exchange Id
         */
        exchange_id: string;
    };
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/llm-exchanges/{exchange_id}';
};

export type GetLlmExchangeApiLlmExchangesExchangeIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLlmExchangeApiLlmExchangesExchangeIdGetError = GetLlmExchangeApiLlmExchangesExchangeIdGetErrors[keyof GetLlmExchangeApiLlmExchangesExchangeIdGetErrors];

export type GetLlmExchangeApiLlmExchangesExchangeIdGetResponses = {
    /**
     * Successful Response
     */
    200: LlmExchangeOut;
};

export type GetLlmExchangeApiLlmExchangesExchangeIdGetResponse = GetLlmExchangeApiLlmExchangesExchangeIdGetResponses[keyof GetLlmExchangeApiLlmExchangesExchangeIdGetResponses];

export type GetRealtimeConfigApiRealtimeConfigGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/realtime/config';
};

export type GetRealtimeConfigApiRealtimeConfigGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRealtimeConfigApiRealtimeConfigGetError = GetRealtimeConfigApiRealtimeConfigGetErrors[keyof GetRealtimeConfigApiRealtimeConfigGetErrors];

export type GetRealtimeConfigApiRealtimeConfigGetResponses = {
    /**
     * Successful Response
     */
    200: RealtimeConfigOut;
};

export type GetRealtimeConfigApiRealtimeConfigGetResponse = GetRealtimeConfigApiRealtimeConfigGetResponses[keyof GetRealtimeConfigApiRealtimeConfigGetResponses];

export type GetPageRunApiPagesPageIdRunGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Page Id
         */
        page_id: string;
    };
    query?: {
        /**
         * Staged Run Id
         */
        staged_run_id?: string | null;
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/pages/{page_id}/run';
};

export type GetPageRunApiPagesPageIdRunGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPageRunApiPagesPageIdRunGetError = GetPageRunApiPagesPageIdRunGetErrors[keyof GetPageRunApiPagesPageIdRunGetErrors];

export type GetPageRunApiPagesPageIdRunGetResponses = {
    /**
     * Response Get Page Run Api Pages  Page Id  Run Get
     *
     * Successful Response
     */
    200: RunSummaryOut | null;
};

export type GetPageRunApiPagesPageIdRunGetResponse = GetPageRunApiPagesPageIdRunGetResponses[keyof GetPageRunApiPagesPageIdRunGetResponses];

export type GetPageLoadStatsApiRunsRunIdPageLoadStatsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: {
        /**
         * Project Id
         */
        project_id?: string;
    };
    url: '/api/runs/{run_id}/page-load-stats';
};

export type GetPageLoadStatsApiRunsRunIdPageLoadStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPageLoadStatsApiRunsRunIdPageLoadStatsGetError = GetPageLoadStatsApiRunsRunIdPageLoadStatsGetErrors[keyof GetPageLoadStatsApiRunsRunIdPageLoadStatsGetErrors];

export type GetPageLoadStatsApiRunsRunIdPageLoadStatsGetResponses = {
    /**
     * Successful Response
     */
    200: PageLoadStatsOut;
};

export type GetPageLoadStatsApiRunsRunIdPageLoadStatsGetResponse = GetPageLoadStatsApiRunsRunIdPageLoadStatsGetResponses[keyof GetPageLoadStatsApiRunsRunIdPageLoadStatsGetResponses];
